### ISSUE TITLE
CryptographySuite setting is not applied to the user tunnel

### ISSUE THREAD

**Issue by jonatanhovgaard** [richardhicks/aovpn#10]
When using "<NativeProtocolType>Automatic</NativeProtocolType>" the IKEv2 configuration is not applied to the "user tunnel". If NativeProtolType is set to IKEv2 the crypto settings will be applied succesfully. I have seen this in several installations. As your ProfileXML configuration works with both a "device tunnel" configuration and a "user tunnel" configured with IKEv2, I suspect this to be a Microsoft issue, but I just thought you should know.

**Comment by richardhicks** [comment]
Indeed, this is a known issue with Microsoft. For some reason, Windows ignores the cryptography settings when the NativeProtocolType is set to Automatic. :/ 

More details here: https://directaccess.richardhicks.com/2019/01/07/always-on-vpn-ikev2-connection-failure-error-code-800/

Thanks!

**Comment by jonatanhovgaard** [comment]
Thanks a lot for your reply and thanks for all the relevant info on AOVPN you provide to all of us via your website and github account. 😊

**Comment by richardhicks** [comment]
My pleasure! :)
