### ISSUE TITLE
New-AovpnConnection success message always mentions user tunnel

### ISSUE THREAD

**Issue by IJustKnowStuff** [richardhicks/aovpn#11]
This is small, but it caught me out at first when testing the tunnel configured correctly after migrating from using your separate Device and non-Device scripts to the single new-aovpnconnection script.

The success message has "user tunnel" hard coded even though the script also now configures device tunnels.

`Write-Output "Always On VPN user tunnel profile ""$ProfileName"" created successfully."`

**Comment by richardhicks** [comment]
Thanks for catching that! Indeed, this script started out life as a user tunnel script, but then later I added support for both user tunnel and device tunnel in the same script. I obviously didn't update the message output. I'll address that now.

**Comment by richardhicks** [comment]
Issue fixed. New signed script uploaded.
