### ISSUE TITLE
Remove-AovpnConnection CleanupOnly doesn't work

### ISSUE THREAD

**Issue by timwsuqld** [richardhicks/aovpn#17]
The logic for CleanUpOnly doesn't appear to work anymore. We only do the cleanup if `If ($ProfileRemoved)` which is always false unless we've run the code in the first if block, which is skipped when `CleanUpOnly` is true.

**Comment by richardhicks** [comment]
Thanks for bringing that to my attention! I'll have a look soon and correct that. :)

**Comment by richardhicks** [comment]
Issue correct. Please download and test again. It should work as expected now. Thanks again!
