### ISSUE TITLE
Set-IKEv2VpnRootCertificate.ps1 Custom EKU OID?

### ISSUE THREAD

**Issue by lplpmc** [richardhicks/aovpn#21]
On 2016 i am able to configure my custom cert OIDs for user/device tunnel certificates using:

CertificateEKUsToAccept       : {Contoso AlwaysOnVPN, Contoso AlwaysOnVPN - DeviceTunnel}

I am unable to use this same configuration on server 2022 

I have tried using the oid values as well without success.

Do you have any insight on this issue?
Thanks for your time,

**Comment by richardhicks** [comment]
I've been using this for quite some time on Windows Server 2022 without issue. Can you tell me exactly what command syntax you used and what error you received? A screenshot would be perfect. Thanks!
