### ISSUE TITLE
New-Aovpnconnection.ps1 fails to create user tunnel for all user connection

### ISSUE THREAD

**Issue by ETx13** [richardhicks/aovpn#22]
When trying to use the -AllUserConnection parameter I get the the following error: _Unable to create "Always On VPN (User)" profile: Exception calling "CreateInstance" with "2" argument(s): "A general error occurred that is not covered by a more specific error code."_

I've tested the script for an individual user and it worked. Also, this is being run as "system" as per the script instructions.

**Comment by richardhicks** [comment]
Can you provide me with the exact command line arguments you used when you received this error message?
