### ISSUE TITLE
Registry error  (RasMan) at device tunnel creation

### ISSUE THREAD

**Issue by Supaxor** [richardhicks/aovpn#23]
Hi,

I tried to configure AlwaysOn Device Tunnel but when I start the script as system user (planned task), I got the following error in powershell logs :
_Erreur de terminaison (Get-ItemPropertyValue) : « L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Impossible de trouver le chemin d'accès « HKLM:\System\CurrentControlSet\Services\RasMan\Config\ », car il n'existe pas. »
Unable to create "VPN Device Tunnel" profile: Exception lors de l'appel de « CreateInstance » avec « 2 » argument(s) : « Une erreur générale qui n’est pas couverte par un code d’erreur plus spécifique s’est produite. »_

I saw that this registry key do not exist on Windows 11 Enterprise ou Windows 10 Pro. What should I do ?
Thank you, Regards,

**Comment by nilv69** [comment]
Hello, have you tried a name without spaces?

**Comment by Supaxor** [comment]
No, but I think the problem is not in the name, but in this line: 
![image](https://github.com/user-attachments/assets/5a295370-efe8-46a4-8e10-65b58e7349d3)

**Comment by richardhicks** [comment]
The -ErrorAction Stop should trigger the Catch block which returns a verbose message indicating the registry path does not exist. Does your error message indicate which line the error occurred? Also, it's possible this is a localization issue. I've only ever tested this script using the EN-US language.

**Comment by Supaxor** [comment]
I only have what you see on screen (in a French OS), the script stop because _HKLM:\System\CurrentControlSet\Services\RasMan\Config\_ doesn't exist

**Comment by richardhicks** [comment]
Ok, thanks. Again, that section of code should trigger the Catch block and surface a verbose message. Why that's not happening for you I have no idea. I suspect a localization issue because I don't have this problem on EN-US versions of Windows. Is there any way you could test on a machine with EN-US language installed? I'd be curious to know if the problem still exists for you there.

**Comment by richardhicks** [comment]
Also, do you get this error if you run the script interactively as SYSTEM, not as a scheduled task?

**Comment by Supaxor** [comment]
I got the exact same thing : 
![image](https://github.com/user-attachments/assets/d8da2343-5764-4e58-bb9c-77042bf83657)

I tried with a shorter name and without name, each time the same issue. 
I didn't have the time to install a full vm in US yet. But even if it works that will not resolve this issue.

**Comment by richardhicks** [comment]
I agree that using EN-US isn't a valid workaround, but it would at least tell me if it was a localization issue, which is what I suspect. Have you tried running this command on another endpoint? If so, do you get the same result?

**Comment by Supaxor** [comment]
Hi, I installed a windows 11 Ent in EN-US, and I have the exact same issue :
![image](https://github.com/user-attachments/assets/319c9025-37f6-4394-a4ba-ed294d4577a5)

I think you don't have this error because the registry key already exist on your system because of previous configurations. But that does not explain what I seems to be the only one to get this error. Maybe a new powershell version ?

I could just comment this section in the script, or manually create the registry key but if I can help improving this script for other users ... :)

**Comment by richardhicks** [comment]
What version of Windows 11? 24H2? I've not had any issues with the script before this, even with a fresh new install. However, I've not tested my script on 24H2 yet.

**Comment by Supaxor** [comment]
yes the two OS are up to date

**Comment by richardhicks** [comment]
Ok. I'll do some testing now with Windows 11 24H2 and see if I can reproduce. I'll let you know as soon as I know more.

**Comment by richardhicks** [comment]
So, I just finished spinning up a clean Windows 11 Enterprise 24H2 virtual machine. I tested installing the device tunnel both before and after updates. I'm still unable to reproduce! I have no idea why you are consistently seeing this issue. :/

**Comment by Supaxor** [comment]
After Richard took the time to help me, the error has nothing to do with the shown message about registry key. I had an excedent dot in my XML file. Everything works fine now. Thanks again Richard!
