### ISSUE TITLE
General Error - New-AovpnConnection.ps1

### ISSUE THREAD

**Issue by AnimatedAneurin** [richardhicks/aovpn#24]
When attempting to run the script with the command listed below, I am faced with an error. I've made sure that I'm running it as SYSTEM by using psexec, I'm also using the execution policy bypass command to avoid PowerShell Policy issues. Unsure what may be causing this, any ideas?

Command Used:
powershell.exe -ep bypass -f ".\New-AovpnConnection.ps1" -xmlFilePath ".\AOVPN-UserTunnel-Config.xml" -ProfileName "Always On VPN" -AllUserConnection

Error Received:
Unable to create "Always On VPN" profile: Exception calling "CreateInstance" with "2" argument(s): "A general error occurred that is not covered by a more specific error code."

**Comment by richardhicks** [comment]
There are a number of potential causes for this issue. The most common is a syntax error in your XML configuration file. If you can share it with me I'd be happy to review and test. Thanks!

**Comment by AnimatedAneurin** [comment]
So after reviewing my XML configuration file, I've managed to fix the issue by starting from scratch. Think I may have had a bad character somewhere, so user error on my part. Thanks for the help!

**Comment by richardhicks** [comment]
You're not the first person that's happened to. Glad you got it sorted out! :)
