### ISSUE TITLE
Corruption of rasphone.pbk after invoking

### ISSUE THREAD

**Issue by sc00terMcP** [richardhicks/aovpn#6]
I have been having issues getting this to work properly and the deltas from April 30 to June 4 do not seem to address this.  The file attached was created using the April 30 version.
[rasphone.pbk.corrupt.txt](https://github.com/richardhicks/aovpn/files/4748603/rasphone.pbk.corrupt.txt)
[rasphone.pbk.txt](https://github.com/richardhicks/aovpn/files/4748604/rasphone.pbk.txt)

Invoking via SCCM as a Package, deployed to a User, so it runs in the user context.

The computer is currently running 1809, with a User based Always On VPN connection that is connected at the time of running.

It is invoked as a bat file as such:
@ECHO OFF
SET MyDirectory=%~dp0
SET PowerShellScriptPath=%~dp0Update-RasPhone.ps1
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& '%PowerShellScriptPath%' -ProfileName 'REDACTED_VPN' -InterfaceMetric 1"

Attached is a working rasphone.pbk prior to running the script and the corrupt pbk from after the script running.  Notice the increased size and "Collections.ArrayList" entries.

Any ideas?

**Comment by richardhicks** [comment]
Sorry to hear about the trouble! I'll have a look ASAP and let you know what I find!

**Comment by richardhicks** [comment]
Confirmed issue with SCCM.
